// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdl8tArMXFTbm2RglTiRGZFLbtw2yvE4Y',
    appId: '1:741818077221:web:811538e3693ab85625afcc',
    messagingSenderId: '741818077221',
    projectId: 'flutter-trivia-2bc98',
    authDomain: 'flutter-trivia-2bc98.firebaseapp.com',
    storageBucket: 'flutter-trivia-2bc98.firebasestorage.app',
    measurementId: 'G-F1SSYPJKJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsTtj7jQ7xaHDCzLClDoueW_8zwxiPzfY',
    appId: '1:741818077221:android:4647c7c5cebcf6b825afcc',
    messagingSenderId: '741818077221',
    projectId: 'flutter-trivia-2bc98',
    storageBucket: 'flutter-trivia-2bc98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuXyYhS6KP-ARi1b7nrikrd0BVjP7p8Is',
    appId: '1:741818077221:ios:c7169882f396616825afcc',
    messagingSenderId: '741818077221',
    projectId: 'flutter-trivia-2bc98',
    storageBucket: 'flutter-trivia-2bc98.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuXyYhS6KP-ARi1b7nrikrd0BVjP7p8Is',
    appId: '1:741818077221:ios:c7169882f396616825afcc',
    messagingSenderId: '741818077221',
    projectId: 'flutter-trivia-2bc98',
    storageBucket: 'flutter-trivia-2bc98.firebasestorage.app',
    iosBundleId: 'com.example.flutterTrivia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdl8tArMXFTbm2RglTiRGZFLbtw2yvE4Y',
    appId: '1:741818077221:web:94eb151794622acd25afcc',
    messagingSenderId: '741818077221',
    projectId: 'flutter-trivia-2bc98',
    authDomain: 'flutter-trivia-2bc98.firebaseapp.com',
    storageBucket: 'flutter-trivia-2bc98.firebasestorage.app',
    measurementId: 'G-THC0S7E6WW',
  );
}
